### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chenxofhit** [GregaVrbancic/spring-atmosphere-chat-example#1]
java.lang.IllegalArgumentException
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)
	at org.springframework.asm.ClassReader.<init>(Unknown Source)

**Comment by GregaVrbancic** [comment]
Hi! Could you please provide more informations regarding your issue?
